// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: v1/srvmon.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status represents the health status of a component.
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_UP          Status = 1
	Status_STATUS_DOWN        Status = 2
	Status_STATUS_DEGRADED    Status = 3
	Status_STATUS_UNKNOWN     Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_UP",
		2: "STATUS_DOWN",
		3: "STATUS_DEGRADED",
		4: "STATUS_UNKNOWN",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_UP":          1,
		"STATUS_DOWN":        2,
		"STATUS_DEGRADED":    3,
		"STATUS_UNKNOWN":     4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_srvmon_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_v1_srvmon_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_v1_srvmon_proto_rawDescGZIP(), []int{0}
}

// CheckResult represents the outcome of a single health check.
type CheckResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name identifies the checker that produced this result.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// status indicates the health status.
	Status Status `protobuf:"varint,2,opt,name=status,proto3,enum=srvmon.v1.Status" json:"status,omitempty"`
	// message provides additional context about the check result.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// timestamp is when the check was performed.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// error contains the error message if the check failed.
	Error         string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResult) Reset() {
	*x = CheckResult{}
	mi := &file_v1_srvmon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResult) ProtoMessage() {}

func (x *CheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_v1_srvmon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResult.ProtoReflect.Descriptor instead.
func (*CheckResult) Descriptor() ([]byte, []int) {
	return file_v1_srvmon_proto_rawDescGZIP(), []int{0}
}

func (x *CheckResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CheckResult) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *CheckResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckResult) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *CheckResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// HealthRequest is the request for the Health RPC.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_v1_srvmon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_srvmon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_v1_srvmon_proto_rawDescGZIP(), []int{1}
}

// HealthResponse is the response from the Health RPC.
type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status is the overall health status.
	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=srvmon.v1.Status" json:"status,omitempty"`
	// version is the service version.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// checks contains individual check results.
	Checks []*CheckResult `protobuf:"bytes,3,rep,name=checks,proto3" json:"checks,omitempty"`
	// timestamp is when the report was generated.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_v1_srvmon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_srvmon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_v1_srvmon_proto_rawDescGZIP(), []int{2}
}

func (x *HealthResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetChecks() []*CheckResult {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *HealthResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// ReadinessRequest is the request for the Readiness RPC.
type ReadinessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadinessRequest) Reset() {
	*x = ReadinessRequest{}
	mi := &file_v1_srvmon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadinessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadinessRequest) ProtoMessage() {}

func (x *ReadinessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_srvmon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadinessRequest.ProtoReflect.Descriptor instead.
func (*ReadinessRequest) Descriptor() ([]byte, []int) {
	return file_v1_srvmon_proto_rawDescGZIP(), []int{3}
}

// ReadinessResponse is the response from the Readiness RPC.
type ReadinessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ready indicates if the service can handle requests.
	Ready bool `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	// reason explains why the service is not ready.
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// checks contains individual readiness check results.
	Checks []*CheckResult `protobuf:"bytes,3,rep,name=checks,proto3" json:"checks,omitempty"`
	// timestamp is when the report was generated.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadinessResponse) Reset() {
	*x = ReadinessResponse{}
	mi := &file_v1_srvmon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadinessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadinessResponse) ProtoMessage() {}

func (x *ReadinessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_srvmon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadinessResponse.ProtoReflect.Descriptor instead.
func (*ReadinessResponse) Descriptor() ([]byte, []int) {
	return file_v1_srvmon_proto_rawDescGZIP(), []int{4}
}

func (x *ReadinessResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *ReadinessResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ReadinessResponse) GetChecks() []*CheckResult {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *ReadinessResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_v1_srvmon_proto protoreflect.FileDescriptor

const file_v1_srvmon_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/srvmon.proto\x12\tsrvmon.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb6\x01\n" +
	"\vCheckResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x06status\x18\x02 \x01(\x0e2\x11.srvmon.v1.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\x0f\n" +
	"\rHealthRequest\"\xbf\x01\n" +
	"\x0eHealthResponse\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.srvmon.v1.StatusR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12.\n" +
	"\x06checks\x18\x03 \x03(\v2\x16.srvmon.v1.CheckResultR\x06checks\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x12\n" +
	"\x10ReadinessRequest\"\xab\x01\n" +
	"\x11ReadinessResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12.\n" +
	"\x06checks\x18\x03 \x03(\v2\x16.srvmon.v1.CheckResultR\x06checks\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp*i\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTATUS_UP\x10\x01\x12\x0f\n" +
	"\vSTATUS_DOWN\x10\x02\x12\x13\n" +
	"\x0fSTATUS_DEGRADED\x10\x03\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x042\x8b\x01\n" +
	"\x06srvmon\x12=\n" +
	"\x06Health\x12\x18.srvmon.v1.HealthRequest\x1a\x19.srvmon.v1.HealthResponse\x12B\n" +
	"\x05Ready\x12\x1b.srvmon.v1.ReadinessRequest\x1a\x1c.srvmon.v1.ReadinessResponseB-Z+github.com/s4bb4t/srvmon/pkg/grpc/srvmon/v1b\x06proto3"

var (
	file_v1_srvmon_proto_rawDescOnce sync.Once
	file_v1_srvmon_proto_rawDescData []byte
)

func file_v1_srvmon_proto_rawDescGZIP() []byte {
	file_v1_srvmon_proto_rawDescOnce.Do(func() {
		file_v1_srvmon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_srvmon_proto_rawDesc), len(file_v1_srvmon_proto_rawDesc)))
	})
	return file_v1_srvmon_proto_rawDescData
}

var file_v1_srvmon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_srvmon_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1_srvmon_proto_goTypes = []any{
	(Status)(0),                   // 0: srvmon.v1.Status
	(*CheckResult)(nil),           // 1: srvmon.v1.CheckResult
	(*HealthRequest)(nil),         // 2: srvmon.v1.HealthRequest
	(*HealthResponse)(nil),        // 3: srvmon.v1.HealthResponse
	(*ReadinessRequest)(nil),      // 4: srvmon.v1.ReadinessRequest
	(*ReadinessResponse)(nil),     // 5: srvmon.v1.ReadinessResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_v1_srvmon_proto_depIdxs = []int32{
	0, // 0: srvmon.v1.CheckResult.status:type_name -> srvmon.v1.Status
	6, // 1: srvmon.v1.CheckResult.timestamp:type_name -> google.protobuf.Timestamp
	0, // 2: srvmon.v1.HealthResponse.status:type_name -> srvmon.v1.Status
	1, // 3: srvmon.v1.HealthResponse.checks:type_name -> srvmon.v1.CheckResult
	6, // 4: srvmon.v1.HealthResponse.timestamp:type_name -> google.protobuf.Timestamp
	1, // 5: srvmon.v1.ReadinessResponse.checks:type_name -> srvmon.v1.CheckResult
	6, // 6: srvmon.v1.ReadinessResponse.timestamp:type_name -> google.protobuf.Timestamp
	2, // 7: srvmon.v1.srvmon.Health:input_type -> srvmon.v1.HealthRequest
	4, // 8: srvmon.v1.srvmon.Ready:input_type -> srvmon.v1.ReadinessRequest
	3, // 9: srvmon.v1.srvmon.Health:output_type -> srvmon.v1.HealthResponse
	5, // 10: srvmon.v1.srvmon.Ready:output_type -> srvmon.v1.ReadinessResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_v1_srvmon_proto_init() }
func file_v1_srvmon_proto_init() {
	if File_v1_srvmon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_srvmon_proto_rawDesc), len(file_v1_srvmon_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_srvmon_proto_goTypes,
		DependencyIndexes: file_v1_srvmon_proto_depIdxs,
		EnumInfos:         file_v1_srvmon_proto_enumTypes,
		MessageInfos:      file_v1_srvmon_proto_msgTypes,
	}.Build()
	File_v1_srvmon_proto = out.File
	file_v1_srvmon_proto_goTypes = nil
	file_v1_srvmon_proto_depIdxs = nil
}
