// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: v1/srvmon.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Srvmon_Health_FullMethodName = "/srvmon.v1.srvmon/Health"
	Srvmon_Ready_FullMethodName  = "/srvmon.v1.srvmon/Ready"
)

// SrvmonClient is the client API for Srvmon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// srvmon provides health check endpoints for monitoring.
type SrvmonClient interface {
	// Health returns the overall health status of the service.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Readiness indicates if the service is ready to accept traffic.
	Ready(ctx context.Context, in *ReadinessRequest, opts ...grpc.CallOption) (*ReadinessResponse, error)
}

type srvmonClient struct {
	cc grpc.ClientConnInterface
}

func NewSrvmonClient(cc grpc.ClientConnInterface) SrvmonClient {
	return &srvmonClient{cc}
}

func (c *srvmonClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Srvmon_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvmonClient) Ready(ctx context.Context, in *ReadinessRequest, opts ...grpc.CallOption) (*ReadinessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadinessResponse)
	err := c.cc.Invoke(ctx, Srvmon_Ready_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SrvmonServer is the server API for Srvmon service.
// All implementations must embed UnimplementedSrvmonServer
// for forward compatibility.
//
// srvmon provides health check endpoints for monitoring.
type SrvmonServer interface {
	// Health returns the overall health status of the service.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Readiness indicates if the service is ready to accept traffic.
	Ready(context.Context, *ReadinessRequest) (*ReadinessResponse, error)
	mustEmbedUnimplementedSrvmonServer()
}

// UnimplementedSrvmonServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSrvmonServer struct{}

func (UnimplementedSrvmonServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedSrvmonServer) Ready(context.Context, *ReadinessRequest) (*ReadinessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ready not implemented")
}
func (UnimplementedSrvmonServer) mustEmbedUnimplementedSrvmonServer() {}
func (UnimplementedSrvmonServer) testEmbeddedByValue()                {}

// UnsafeSrvmonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SrvmonServer will
// result in compilation errors.
type UnsafeSrvmonServer interface {
	mustEmbedUnimplementedSrvmonServer()
}

func RegisterSrvmonServer(s grpc.ServiceRegistrar, srv SrvmonServer) {
	// If the following call panics, it indicates UnimplementedSrvmonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Srvmon_ServiceDesc, srv)
}

func _Srvmon_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvmonServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Srvmon_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvmonServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Srvmon_Ready_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvmonServer).Ready(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Srvmon_Ready_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvmonServer).Ready(ctx, req.(*ReadinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Srvmon_ServiceDesc is the grpc.ServiceDesc for Srvmon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Srvmon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "srvmon.v1.srvmon",
	HandlerType: (*SrvmonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _Srvmon_Health_Handler,
		},
		{
			MethodName: "Ready",
			Handler:    _Srvmon_Ready_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/srvmon.proto",
}
